### ISSUE TITLE
Error in "Vulnerability analysis for the node pairs(VPPs)"

### ISSUE THREAD

**Issue by wangze09** [kr-swapnil/NetVA#1]
Hi Kumar,
That's a really practical tool! But when I tried the function of detection of VPPs,
```
v.list = combn(v, 2, simplify = FALSE)
netva.res <- netva(v.list, bc.net, ncore = 1)
``` 
I met a error like this
```
*** NetVA v1.0.0 with normal mode ***
Error in cl$membership[[i]] : 
  attempt to select more than one element in vectorIndex
```
Could you help me to check the problem? Thanks a lot!
Yours sincerely, Ze

**Comment by kr-swapnil** [comment]
Hi @wangze09, 

There was an issue with the package's 'cohesiveness' function behind the error.

I have fixed it now, and the function 'netva' works fine for protein pairs/triplets. However, please re-install the package before using any of its functions again.

Thanking you

With regards,

Swapnil

**Comment by wangze09** [comment]
> Hi @wangze09,
> 
> There was an issue with the package's 'cohesiveness' function behind the error.
> 
> I have fixed it now, and the function 'netva' works fine for protein pairs/triplets. However, please re-install the package before using any of its functions again.
> 
> Thanking you
> 
> With regards,
> 
> Swapnil

Thanks a lot! Have a nice weekend!
Ze
